# Generated by Django 5.2.1 on 2025-05-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('file', models.FileField(upload_to='cvs/')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True)),
            ],
        ),
    ]
